In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/playground-series-s6e2/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e2/train.csv
/kaggle/input/competitions/playground-series-s6e2/test.csv
/kaggle/input/notebooks/kumarkatariya/stacking-xbg-xgb-fe-lr-lgbm-seed-avg-ratio-f-tabm/__results__.html
/kaggle/input/notebooks/kumarkatariya/stacking-xbg-xgb-fe-lr-lgbm-seed-avg-ratio-f-tabm/submission.csv
/kaggle/input/notebooks/kumarkatariya/stacking-xbg-xgb-fe-lr-lgbm-seed-avg-ratio-f-tabm/__notebook__.ipynb
/kaggle/input/notebooks/kumarkatariya/stacking-xbg-xgb-fe-lr-lgbm-seed-avg-ratio-f-tabm/__output__.json
/kaggle/input/notebooks/kumarkatariya/stacking-xbg-xgb-fe-lr-lgbm-seed-avg-ratio-f-tabm/custom.css
/kaggle/input/notebooks/kumarkatariya/ensemble-xbg-xgb-fe-lr-lgbm-seed-avg-tabm/__results__.html
/kaggle/input/notebooks/kumarkatariya/ensemble-xbg-xgb-fe-lr-lgbm-seed-avg-tabm/submission.csv
/kaggle/input/notebooks/kumarkatariya/ensemble-xbg-xgb-fe-lr-lgbm-seed-avg-tabm/__notebook__.ipynb
/kaggle/input/notebooks/kumarkatariya/ensemble-xbg-xgb-fe-lr-lgbm-seed-avg-tabm/__output__.json
/kaggle/input/notebooks/kumarkatariya/ensemble-xbg-xgb-fe-lr-lgbm-seed-avg-tabm/custom.css
/kaggle/input/notebooks/kumarkatariya/ensemble-xbg-xgb-fe-lr-lgbm-seed-avg-tabm/__results___files/__results___23_1.png

In [2]:
stacking = pd.read_csv('/kaggle/input/notebooks/kumarkatariya/stacking-xbg-xgb-fe-lr-lgbm-seed-avg-ratio-f-tabm/submission.csv')
ensemble = pd.read_csv('/kaggle/input/notebooks/kumarkatariya/ensemble-xbg-xgb-fe-lr-lgbm-seed-avg-tabm/submission.csv')

In [3]:
stacking.head()

       id  Heart Disease
0  630000       0.712911
1  630001       0.272523
2  630002       0.726788
3  630003       0.270197
4  630004       0.346641

In [4]:
ensemble.head()

       id  Heart Disease
0  630000       0.958324
1  630001       0.008434
2  630002       0.989371
3  630003       0.003765
4  630004       0.176641

In [5]:
test_df = pd.read_csv('/kaggle/input/competitions/playground-series-s6e2/test.csv')

In [6]:
test_df.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,630000,58,1,3,120,288,0,2,145,1,0.8,2,3,3
1,630001,55,0,2,120,209,0,0,172,0,0.0,1,0,3
2,630002,54,1,4,120,268,0,0,150,1,0.0,2,3,7
3,630003,44,0,3,112,177,0,0,168,0,0.9,1,0,3
4,630004,43,1,1,138,267,0,0,163,0,1.8,2,0,7

In [7]:
test_ids = test_df['id']

In [8]:
final_pred = (stacking['Heart Disease']*0.6) + (ensemble['Heart Disease']*0.4)

In [9]:
submission = pd.DataFrame({
    'id':test_ids,
    'Heart Disease':final_pred
})

In [10]:
submission.to_csv('submission.csv',index=False)